language: python

env:
  - TOXENV=docs
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

before_install:
  - "[ -d ~/.distlib ] && sudo chown -R travis:travis ~/.distlib || true"

install:
  - sudo apt-get install subversion bzr mercurial
  - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
  - git config --global user.email "python-virtualenv@googlegroups.com"
  - git config --global user.name "Pip"
  - pip install --upgrade setuptools
  - pip install tox

script: tox

branches:
  only:
    - develop
    - 1.3.X
    - 1.4.X
    - 1.5.X

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
