# Generated by Django 2.0.7 on 2020-02-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostLoginifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='主机IP信息')),
                ('ssh_port', models.CharField(max_length=32, null=True, verbose_name='ssh登录的端口')),
                ('ssh_user', models.CharField(max_length=32, null=True, verbose_name='ssh登录的用户')),
                ('ssh_passwd', models.CharField(default='', max_length=64, null=True, verbose_name='ssh登录的用户')),
                ('ssh_rsa', models.CharField(default='', max_length=64, null=True, verbose_name='登录使用的私钥')),
                ('rsa_pass', models.CharField(default='', max_length=64, null=True, verbose_name='私钥的秘药')),
                ('system_ver', models.CharField(default='', max_length=256, null=True, verbose_name='操作系统版本')),
                ('hostname', models.CharField(default='', max_length=256, null=True, verbose_name='操作系统主机名')),
                ('ssh_status', models.IntegerField(default=0, verbose_name='0-登录失败,1-登录成功')),
                ('ssh_type', models.IntegerField(default=0, verbose_name='1-rsa登录,2-dsa登录,3-普通用户rsa登录,4-docker成功,5-docker无法登录')),
                ('mac_address', models.CharField(default='', max_length=512, verbose_name='mac地址列表')),
                ('sn', models.CharField(default='', max_length=256, verbose_name='SN－主机的唯一标示')),
                ('mathine_type', models.CharField(default='', max_length=256, verbose_name='机器的类型 1=物理服务器,2=虚拟资产,3=网络设备 0=其他类型(未知)')),
                ('sn_key', models.CharField(default='', max_length=256, verbose_name='唯一设备ID')),
                ('host_type', models.CharField(default='', max_length=256, null=True, verbose_name='虚拟机上宿主机的类型')),
            ],
            options={
                'verbose_name': '初始化扫描信息表',
                'verbose_name_plural': '初始化扫描信息表',
                'db_table': 'hostloginifo',
            },
        ),
    ]
