# Generated by Django 2.0.7 on 2020-02-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineOperationsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='操作序号')),
                ('person', models.CharField(default='', max_length=20, verbose_name='操作人用户名')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('sn_key', models.CharField(max_length=250, unique=True, verbose_name='设备的唯一标识')),
                ('machine_type', models.CharField(max_length=20, verbose_name='设备类型')),
                ('operation', models.TextField(choices=[(0, '增加'), (1, '删除'), (2, '修改')], default='', verbose_name='操作内容')),
                ('state', models.IntegerField(choices=[(0, '已报废'), (1, '测试使用'), (2, '线上运行'), (3, '下线')], default=2, verbose_name='设备使用状态')),
                ('remark', models.TextField(default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备操作记录表',
                'verbose_name_plural': '设备操作记录表',
                'db_table': 'machineoperationsinfo',
            },
        ),
    ]
